import { existsSync, readFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import path from "node:path";
import { fileURLToPath } from "node:url";

export type ReleaseContextFinding = {
  code: string;
  message: string;
};

const REQUIRED_DOCKERIGNORE_PATTERNS = [
  "node_modules",
  ".git",
  ".github",
  ".env",
  ".env.*",
  "!.env.example",
  ".agentic",
  "**/.agentic",
  "artifacts",
  "**/artifacts",
  ".playwright-mcp",
  "coverage",
  "playwright-report",
  "test-results",
  ".next",
  "apps/web/.next",
  "build",
  ".DS_Store",
  "**/.DS_Store",
  "*.log",
  "*.pem",
  "*.key",
  "*.p12",
  "*.pfx",
  "*.tgz",
  "*.tar"
] as const;

const FORBIDDEN_TRACKED_PATHS: Array<{ code: string; pattern: RegExp; allow?: RegExp; reason: string }> = [
  {
    code: "tracked-env-file",
    pattern: /(^|\/)\.env(?:\.|$)/u,
    allow: /^\.env\.example$/u,
    reason: "environment files may contain local secrets"
  },
  {
    code: "tracked-local-store",
    pattern: /(^|\/)\.agentic(?:\/|$)/u,
    reason: "file-backed runtime stores are machine-local state"
  },
  {
    code: "tracked-release-artifact",
    pattern: /^artifacts\//u,
    reason: "release evidence is generated per build"
  },
  {
    code: "tracked-coverage",
    pattern: /(^|\/)coverage\//u,
    reason: "coverage output is generated"
  },
  {
    code: "tracked-playwright-output",
    pattern: /(^|\/)(playwright-report|test-results)\//u,
    reason: "browser test output is generated"
  },
  {
    code: "tracked-desktop-metadata",
    pattern: /(^|\/)\.DS_Store$/u,
    reason: "desktop metadata is machine-local"
  },
  {
    code: "tracked-private-key",
    pattern: /\.(?:pem|key|p12|pfx)$/u,
    reason: "private key material must not be tracked"
  },
  {
    code: "tracked-packed-artifact",
    pattern: /\.(?:tgz|tar)$/u,
    reason: "packed release artifacts must be generated by CI"
  }
];

function repoRoot(): string {
  return path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
}

function normalizeDockerIgnore(content: string): Set<string> {
  return new Set(
    content
      .split(/\r?\n/u)
      .map((line) => line.trim())
      .filter((line) => line && !line.startsWith("#"))
  );
}

export function validateDockerIgnoreContent(content: string): ReleaseContextFinding[] {
  const patterns = normalizeDockerIgnore(content);
  return REQUIRED_DOCKERIGNORE_PATTERNS.flatMap((pattern) =>
    patterns.has(pattern)
      ? []
      : [
          {
            code: "missing-dockerignore-pattern",
            message: `.dockerignore must include ${pattern}`
          }
        ]
  );
}

export function validateTrackedReleasePaths(paths: string[]): ReleaseContextFinding[] {
  const findings: ReleaseContextFinding[] = [];

  for (const filePath of paths) {
    for (const rule of FORBIDDEN_TRACKED_PATHS) {
      if (rule.allow?.test(filePath)) {
        continue;
      }

      if (rule.pattern.test(filePath)) {
        findings.push({
          code: rule.code,
          message: `${filePath} is tracked but ${rule.reason}`
        });
      }
    }
  }

  return findings;
}

function listTrackedFiles(cwd: string): string[] {
  const output = execFileSync("git", ["ls-files", "-z"], {
    cwd,
    encoding: "utf8"
  });

  return output.split("\0").filter(Boolean);
}

function main() {
  const cwd = repoRoot();
  const dockerIgnorePath = path.join(cwd, ".dockerignore");
  const findings: ReleaseContextFinding[] = [];

  if (!existsSync(dockerIgnorePath)) {
    findings.push({
      code: "missing-dockerignore",
      message: ".dockerignore is required before building public release images"
    });
  } else {
    findings.push(...validateDockerIgnoreContent(readFileSync(dockerIgnorePath, "utf8")));
  }

  findings.push(...validateTrackedReleasePaths(listTrackedFiles(cwd)));

  if (findings.length === 0) {
    console.log("Release context checks passed.");
    return;
  }

  console.error("Release context checks failed:");
  for (const finding of findings) {
    console.error(`- [${finding.code}] ${finding.message}`);
  }
  process.exitCode = 1;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  main();
}
